### ISSUE TITLE
client fault throws errors

### ISSUE THREAD

**Issue by Asapros** [misiekii123/meteALOlogia-website#2]
E.g. accessing a non-existing path throws 
```
SvelteKitError: Not found: (path)
    at resolve2 (file:///app/build/server/index.js:2944:18)
    at resolve (file:///app/build/server/index.js:2777:34)
    at #options.hooks.handle (file:///app/build/server/index.js:3009:71)
    at respond (file:///app/build/server/index.js:2775:43) {
  status: 404,
  text: 'Not Found'
}
```
on the server side despite it being stricly client-side problem (and it's even handled properly with a frontend page)

**Comment by Asapros** [comment]
Resolved in 3ad341299ed3cba2544935482d08f4eca57d8632
